<?php

declare(strict_types=1);

namespace Creatissimo\AmazonAdsApi\Model;

enum DSPInsightFeature: string
{
    case CAMPAIGN_FREQUENCY_CAP = 'CAMPAIGN_FREQUENCY_CAP';
    case LINE_ITEM_APPBLOCKING_TARGETING = 'LINE_ITEM_APPBLOCKING_TARGETING';
    case LINE_ITEM_COLD_START_DEALS = 'LINE_ITEM_COLD_START_DEALS';
    case LINE_ITEM_COLD_START_SEGMENTS = 'LINE_ITEM_COLD_START_SEGMENTS';
    case LINE_ITEM_CONTEXTUAL_TARGETING = 'LINE_ITEM_CONTEXTUAL_TARGETING';
    case LINE_ITEM_DOMAINLIST_TARGETING = 'LINE_ITEM_DOMAINLIST_TARGETING';
    case LINE_ITEM_FREQUENCY_CAP = 'LINE_ITEM_FREQUENCY_CAP';
    case LINE_ITEM_GEO_TARGETING = 'LINE_ITEM_GEO_TARGETING';
    case LINE_ITEM_LARGE_TARGETING = 'LINE_ITEM_LARGE_TARGETING';
    case LINE_ITEM_MAX_BID = 'LINE_ITEM_MAX_BID';
    case LINE_ITEM_MOBILE_DEVICES_TARGETING = 'LINE_ITEM_MOBILE_DEVICES_TARGETING';
    case LINE_ITEM_NARROW_SEGMENTS = 'LINE_ITEM_NARROW_SEGMENTS';
    case LINE_ITEM_SIMILAR_AUDIENCES = 'LINE_ITEM_SIMILAR_AUDIENCES';
    case LINE_ITEM_TOO_FAR_IN_FUTURE = 'LINE_ITEM_TOO_FAR_IN_FUTURE';
    case LINE_ITEM_UNSUPPORTED_CONTEXTUAL_TARGETING = 'LINE_ITEM_UNSUPPORTED_CONTEXTUAL_TARGETING';
    case LINE_ITEM_UNSUPPORTED_KEYWORD_TARGETING = 'LINE_ITEM_UNSUPPORTED_KEYWORD_TARGETING';
}
