<?php

declare(strict_types=1);

namespace Creatissimo\AmazonAdsApi\Model;

enum ErrorCode: string
{
    case ACTION_NOT_SUPPORTED = 'ACTION_NOT_SUPPORTED';
    case ACTIVE_RESOURCE_LIMIT_EXCEEDED = 'ACTIVE_RESOURCE_LIMIT_EXCEEDED';
    case ARCHIVED_PARENT_CANNOT_CREATE = 'ARCHIVED_PARENT_CANNOT_CREATE';
    case ARCHIVED_PARENT_CANNOT_EDIT = 'ARCHIVED_PARENT_CANNOT_EDIT';
    case ARCHIVED_RESOURCE_CANNOT_EDIT = 'ARCHIVED_RESOURCE_CANNOT_EDIT';
    case AUTOCREATED_ENTITY_CANNOT_EDIT = 'AUTOCREATED_ENTITY_CANNOT_EDIT';
    case BAD_REQUEST = 'BAD_REQUEST';
    case CONFLICT = 'CONFLICT';
    case CONTENT_TOO_LARGE = 'CONTENT_TOO_LARGE';
    case DATE_CANNOT_BE_IN_PAST = 'DATE_CANNOT_BE_IN_PAST';
    case DATE_CANNOT_BE_NULL = 'DATE_CANNOT_BE_NULL';
    case DATE_TOO_SOON = 'DATE_TOO_SOON';
    case DUPLICATE_FIELD_VALUE_FOUND = 'DUPLICATE_FIELD_VALUE_FOUND';
    case DUPLICATE_RESOURCE_ID_FOUND = 'DUPLICATE_RESOURCE_ID_FOUND';
    case DURATION_TOO_SHORT = 'DURATION_TOO_SHORT';
    case FEATURE_DISCONTINUED = 'FEATURE_DISCONTINUED';
    case FEATURE_NOT_AVAILABLE = 'FEATURE_NOT_AVAILABLE';
    case FIELD_SIZE_IS_ABOVE_MAXIMUM_LIMIT = 'FIELD_SIZE_IS_ABOVE_MAXIMUM_LIMIT';
    case FIELD_SIZE_IS_BELOW_MINIMUM_LIMIT = 'FIELD_SIZE_IS_BELOW_MINIMUM_LIMIT';
    case FIELD_SIZE_IS_OUT_OF_RANGE = 'FIELD_SIZE_IS_OUT_OF_RANGE';
    case FIELD_VALUE_CANNOT_EDIT = 'FIELD_VALUE_CANNOT_EDIT';
    case FIELD_VALUE_CONTAINS_BLOCKLISTED_WORDS = 'FIELD_VALUE_CONTAINS_BLOCKLISTED_WORDS';
    case FIELD_VALUE_CONTAINS_INVALID_CHARACTERS = 'FIELD_VALUE_CONTAINS_INVALID_CHARACTERS';
    case FIELD_VALUE_IS_ABOVE_MAXIMUM_LIMIT = 'FIELD_VALUE_IS_ABOVE_MAXIMUM_LIMIT';
    case FIELD_VALUE_IS_BELOW_MINIMUM_LIMIT = 'FIELD_VALUE_IS_BELOW_MINIMUM_LIMIT';
    case FIELD_VALUE_IS_EMPTY = 'FIELD_VALUE_IS_EMPTY';
    case FIELD_VALUE_IS_INVALID = 'FIELD_VALUE_IS_INVALID';
    case FIELD_VALUE_IS_NULL = 'FIELD_VALUE_IS_NULL';
    case FIELD_VALUE_IS_OUT_OF_RANGE = 'FIELD_VALUE_IS_OUT_OF_RANGE';
    case FIELD_VALUE_MISMATCH = 'FIELD_VALUE_MISMATCH';
    case FIELD_VALUE_MUST_BE_EMPTY_OR_NULL = 'FIELD_VALUE_MUST_BE_EMPTY_OR_NULL';
    case FIELD_VALUE_NOT_FOUND = 'FIELD_VALUE_NOT_FOUND';
    case FIELD_VALUE_NOT_UNIQUE = 'FIELD_VALUE_NOT_UNIQUE';
    case FORBIDDEN = 'FORBIDDEN';
    case GLOBAL_ATTRIBUTE_UPDATE_RESTRICTED_PORTFOLIO = 'GLOBAL_ATTRIBUTE_UPDATE_RESTRICTED_PORTFOLIO';
    case GLOBAL_ATTRIBUTE_UPDATE_RESTRICTED_STATE = 'GLOBAL_ATTRIBUTE_UPDATE_RESTRICTED_STATE';
    case GLOBAL_CAMPAIGN_SINGLE_ADGROUP_LIMIT = 'GLOBAL_CAMPAIGN_SINGLE_ADGROUP_LIMIT';
    case INTERNAL_ERROR = 'INTERNAL_ERROR';
    case NOT_FOUND = 'NOT_FOUND';
    case PAYMENT_ISSUE = 'PAYMENT_ISSUE';
    case PRODUCT_INELIGIBLE = 'PRODUCT_INELIGIBLE';
    case RESOURCE_DOES_NOT_BELONG_TO_PARENT = 'RESOURCE_DOES_NOT_BELONG_TO_PARENT';
    case RESOURCE_ID_NOT_FOUND = 'RESOURCE_ID_NOT_FOUND';
    case RESOURCE_IS_EMPTY = 'RESOURCE_IS_EMPTY';
    case RESOURCE_IS_IN_TERMINAL_STATE = 'RESOURCE_IS_IN_TERMINAL_STATE';
    case RESOURCE_IS_NULL = 'RESOURCE_IS_NULL';
    case TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
    case TOTAL_RESOURCE_LIMIT_EXCEEDED = 'TOTAL_RESOURCE_LIMIT_EXCEEDED';
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case UNSUPPORTED_MARKETPLACE = 'UNSUPPORTED_MARKETPLACE';
}
